# Generated by Django 6.0.3 on 2026-04-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="Yo'nalish nomi")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="Yo'nalish nomi")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="Yo'nalish nomi")),
                ('degree', models.CharField(max_length=255, verbose_name="Ta'lim darajasi")),
                ('degree_uz', models.CharField(max_length=255, null=True, verbose_name="Ta'lim darajasi")),
                ('degree_en', models.CharField(max_length=255, null=True, verbose_name="Ta'lim darajasi")),
                ('degree_ru', models.CharField(max_length=255, null=True, verbose_name="Ta'lim darajasi")),
                ('education_form', models.CharField(max_length=255, verbose_name="Ta'lim shakli")),
                ('education_form_uz', models.CharField(max_length=255, null=True, verbose_name="Ta'lim shakli")),
                ('education_form_en', models.CharField(max_length=255, null=True, verbose_name="Ta'lim shakli")),
                ('education_form_ru', models.CharField(max_length=255, null=True, verbose_name="Ta'lim shakli")),
                ('duration', models.CharField(max_length=255, verbose_name='Davomiyligi')),
                ('duration_uz', models.CharField(max_length=255, null=True, verbose_name='Davomiyligi')),
                ('duration_en', models.CharField(max_length=255, null=True, verbose_name='Davomiyligi')),
                ('duration_ru', models.CharField(max_length=255, null=True, verbose_name='Davomiyligi')),
                ('contract_amount', models.CharField(max_length=255, verbose_name='Kontrakt summasi')),
                ('contract_amount_uz', models.CharField(max_length=255, null=True, verbose_name='Kontrakt summasi')),
                ('contract_amount_en', models.CharField(max_length=255, null=True, verbose_name='Kontrakt summasi')),
                ('contract_amount_ru', models.CharField(max_length=255, null=True, verbose_name='Kontrakt summasi')),
                ('what_it_gives_text', models.TextField(blank=True, null=True, verbose_name='Dastur sizga nima beradi - matn')),
                ('what_it_gives_text_uz', models.TextField(blank=True, null=True, verbose_name='Dastur sizga nima beradi - matn')),
                ('what_it_gives_text_en', models.TextField(blank=True, null=True, verbose_name='Dastur sizga nima beradi - matn')),
                ('what_it_gives_text_ru', models.TextField(blank=True, null=True, verbose_name='Dastur sizga nima beradi - matn')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='ProgramAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iconka (Class SVG yoki FontAwesome)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='diplomat.program')),
            ],
            options={
                'verbose_name': "Yo'nalish afzalligi",
                'verbose_name_plural': "Yo'nalish afzalliklari",
            },
        ),
        migrations.CreateModel(
            name='ProgramApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('description_uz', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(null=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iconka (Class SVG yoki FontAwesome)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='diplomat.program')),
            ],
            options={
                'verbose_name': 'Bizning yondashuv',
                'verbose_name_plural': 'Bizning yondashuv',
            },
        ),
        migrations.CreateModel(
            name='WhatItGivesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iconka (Class SVG yoki FontAwesome)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_it_gives_items', to='diplomat.program')),
            ],
            options={
                'verbose_name': 'Dastur nima beradi (punkt)',
                'verbose_name_plural': 'Dastur nima beradi (punktlar)',
            },
        ),
    ]
