# Generated by Django 6.0.3 on 2026-04-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(choices=[('Bakalavriat', 'Bakalavriat'), ('Magistratura', 'Magistratura')], max_length=255, verbose_name="Ta'lim darajasi"),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_en',
            field=models.CharField(choices=[('Bakalavriat', 'Bakalavriat'), ('Magistratura', 'Magistratura')], max_length=255, null=True, verbose_name="Ta'lim darajasi"),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_ru',
            field=models.CharField(choices=[('Bakalavriat', 'Bakalavriat'), ('Magistratura', 'Magistratura')], max_length=255, null=True, verbose_name="Ta'lim darajasi"),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_uz',
            field=models.CharField(choices=[('Bakalavriat', 'Bakalavriat'), ('Magistratura', 'Magistratura')], max_length=255, null=True, verbose_name="Ta'lim darajasi"),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_form',
            field=models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Sirtqi', 'Sirtqi'), ('Kechki', 'Kechki')], max_length=255, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_form_en',
            field=models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Sirtqi', 'Sirtqi'), ('Kechki', 'Kechki')], max_length=255, null=True, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_form_ru',
            field=models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Sirtqi', 'Sirtqi'), ('Kechki', 'Kechki')], max_length=255, null=True, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_form_uz',
            field=models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Sirtqi', 'Sirtqi'), ('Kechki', 'Kechki')], max_length=255, null=True, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='programadvantage',
            name='icon',
            field=models.CharField(blank=True, choices=[('fas fa-lightbulb', "💡 Yorug'lik lampasi (G'oya)"), ('fas fa-brain', '🧠 Miya (Aql/Fikrlash)'), ('fas fa-rocket', '🚀 Raketa (Startap/Tezkor)'), ('fas fa-globe', '🌍 Globus (Xalqaro/Tarmoq)'), ('fas fa-handshake', "🤝 Qo'l siqish (Hamkorlik)"), ('fas fa-users', '👥 Foydalanuvchilar (Jamoa)'), ('fas fa-chalkboard-teacher', "👨\u200d🏫 O'qituvchi (Ta'lim)"), ('fas fa-briefcase', '💼 Portfel (Biznes/Karyera)'), ('fas fa-user-tie', '👔 Galstukli foydalanuvchi (Rahbar/Kompetensiya)'), ('fas fa-microchip', '💻 Mikrochip (Raqamli)'), ('fas fa-robot', '🤖 Robot (AI)'), ('fas fa-network-wired', '🔗 Tarmoq (Ekotizim)'), ('fas fa-project-diagram', '📊 Diagramma (Loyiha)'), ('fas fa-chart-line', "📈 O'sish grafigi (Rivojlanish)"), ('fas fa-chess-knight', '♟️ Ot (Strategiya)')], max_length=100, null=True, verbose_name='Iconka'),
        ),
        migrations.AlterField(
            model_name='programapproach',
            name='icon',
            field=models.CharField(blank=True, choices=[('fas fa-lightbulb', "💡 Yorug'lik lampasi (G'oya)"), ('fas fa-brain', '🧠 Miya (Aql/Fikrlash)'), ('fas fa-rocket', '🚀 Raketa (Startap/Tezkor)'), ('fas fa-globe', '🌍 Globus (Xalqaro/Tarmoq)'), ('fas fa-handshake', "🤝 Qo'l siqish (Hamkorlik)"), ('fas fa-users', '👥 Foydalanuvchilar (Jamoa)'), ('fas fa-chalkboard-teacher', "👨\u200d🏫 O'qituvchi (Ta'lim)"), ('fas fa-briefcase', '💼 Portfel (Biznes/Karyera)'), ('fas fa-user-tie', '👔 Galstukli foydalanuvchi (Rahbar/Kompetensiya)'), ('fas fa-microchip', '💻 Mikrochip (Raqamli)'), ('fas fa-robot', '🤖 Robot (AI)'), ('fas fa-network-wired', '🔗 Tarmoq (Ekotizim)'), ('fas fa-project-diagram', '📊 Diagramma (Loyiha)'), ('fas fa-chart-line', "📈 O'sish grafigi (Rivojlanish)"), ('fas fa-chess-knight', '♟️ Ot (Strategiya)')], max_length=100, null=True, verbose_name='Iconka'),
        ),
        migrations.AlterField(
            model_name='whatitgivesitem',
            name='icon',
            field=models.CharField(blank=True, choices=[('fas fa-lightbulb', "💡 Yorug'lik lampasi (G'oya)"), ('fas fa-brain', '🧠 Miya (Aql/Fikrlash)'), ('fas fa-rocket', '🚀 Raketa (Startap/Tezkor)'), ('fas fa-globe', '🌍 Globus (Xalqaro/Tarmoq)'), ('fas fa-handshake', "🤝 Qo'l siqish (Hamkorlik)"), ('fas fa-users', '👥 Foydalanuvchilar (Jamoa)'), ('fas fa-chalkboard-teacher', "👨\u200d🏫 O'qituvchi (Ta'lim)"), ('fas fa-briefcase', '💼 Portfel (Biznes/Karyera)'), ('fas fa-user-tie', '👔 Galstukli foydalanuvchi (Rahbar/Kompetensiya)'), ('fas fa-microchip', '💻 Mikrochip (Raqamli)'), ('fas fa-robot', '🤖 Robot (AI)'), ('fas fa-network-wired', '🔗 Tarmoq (Ekotizim)'), ('fas fa-project-diagram', '📊 Diagramma (Loyiha)'), ('fas fa-chart-line', "📈 O'sish grafigi (Rivojlanish)"), ('fas fa-chess-knight', '♟️ Ot (Strategiya)')], max_length=100, null=True, verbose_name='Iconka'),
        ),
    ]
