# Generated by Django 6.0.3 on 2026-04-09 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0003_alter_program_degree_alter_program_degree_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Ta'lim darajasi nomi")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="Ta'lim darajasi nomi")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="Ta'lim darajasi nomi")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="Ta'lim darajasi nomi")),
            ],
            options={
                'verbose_name': "Ta'lim darajasi",
                'verbose_name_plural': "Ta'lim darajalari",
            },
        ),
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Ta'lim shakli nomi")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="Ta'lim shakli nomi")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="Ta'lim shakli nomi")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="Ta'lim shakli nomi")),
            ],
            options={
                'verbose_name': "Ta'lim shakli",
                'verbose_name_plural': "Ta'lim shakllari",
            },
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree_uz',
        ),
        migrations.RemoveField(
            model_name='program',
            name='education_form_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='education_form_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='education_form_uz',
        ),
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplomat.degree', verbose_name="Ta'lim darajasi"),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplomat.educationform', verbose_name="Ta'lim shakli"),
        ),
    ]
