# Generated by Django 6.0.3 on 2026-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0004_degree_educationform_remove_program_degree_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programadvantage',
            options={'ordering': ['order'], 'verbose_name': "Yo'nalish afzalligi", 'verbose_name_plural': "Yo'nalish afzalliklari"},
        ),
        migrations.AlterModelOptions(
            name='programapproach',
            options={'ordering': ['order'], 'verbose_name': 'Bizning yondashuv', 'verbose_name_plural': 'Bizning yondashuv'},
        ),
        migrations.AlterModelOptions(
            name='whatitgivesitem',
            options={'ordering': ['order'], 'verbose_name': 'Dastur nima beradi (punkt)', 'verbose_name_plural': 'Dastur nima beradi (punktlar)'},
        ),
        migrations.AddField(
            model_name='programadvantage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqam'),
        ),
        migrations.AddField(
            model_name='programapproach',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqam'),
        ),
        migrations.AddField(
            model_name='whatitgivesitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqam'),
        ),
    ]
