# Generated by Django 6.0.3 on 2026-04-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0005_alter_programadvantage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name="Yo'nalish rasmi"),
        ),
    ]
