# Generated by Django 6.0.3 on 2026-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0007_alter_programadvantage_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programadvantage',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Iconka'),
        ),
        migrations.AlterField(
            model_name='programapproach',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Iconka'),
        ),
        migrations.AlterField(
            model_name='whatitgivesitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Iconka'),
        ),
    ]
