# Generated by Django 6.0.3 on 2026-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0008_alter_programadvantage_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order'], 'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqam'),
        ),
    ]
