# Generated by Django 6.0.3 on 2026-04-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0009_alter_program_options_program_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL uchun)'),
        ),
    ]
