# Generated by Django 6.0.3 on 2026-04-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0010_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='contract_price',
            field=models.PositiveIntegerField(default=0, help_text="To'liq raqam, masalan: 24000000", verbose_name="Kontrakt narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.CharField(blank=True, help_text='Masalan: fas fa-briefcase', max_length=100, null=True, verbose_name='Iconka (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='contract_amount',
            field=models.CharField(help_text='Masalan: 24 MLN', max_length=255, verbose_name='Kontrakt summasi (qisqa)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='contract_amount_en',
            field=models.CharField(help_text='Masalan: 24 MLN', max_length=255, null=True, verbose_name='Kontrakt summasi (qisqa)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='contract_amount_ru',
            field=models.CharField(help_text='Masalan: 24 MLN', max_length=255, null=True, verbose_name='Kontrakt summasi (qisqa)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='contract_amount_uz',
            field=models.CharField(help_text='Masalan: 24 MLN', max_length=255, null=True, verbose_name='Kontrakt summasi (qisqa)'),
        ),
    ]
