# Generated by Django 6.0.3 on 2026-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0011_program_contract_price_program_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('icon', models.CharField(blank=True, help_text='Masalan: fas fa-handshake', max_length=100, null=True, verbose_name='Iconka')),
                ('image', models.ImageField(upload_to='campus_gallery/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': 'Kampus Galereyasi',
                'verbose_name_plural': 'Kampus Galereyasi',
                'ordering': ['order'],
            },
        ),
    ]
