# Generated by Django 6.0.3 on 2026-04-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0012_campusgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='F.I.SH.')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('position', models.CharField(max_length=255, verbose_name='Ilmiy daraja va lavozimi')),
                ('position_uz', models.CharField(max_length=255, null=True, verbose_name='Ilmiy daraja va lavozimi')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Ilmiy daraja va lavozimi')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Ilmiy daraja va lavozimi')),
                ('education_history', models.TextField(verbose_name="O'quv faoliyati")),
                ('education_history_uz', models.TextField(null=True, verbose_name="O'quv faoliyati")),
                ('education_history_en', models.TextField(null=True, verbose_name="O'quv faoliyati")),
                ('education_history_ru', models.TextField(null=True, verbose_name="O'quv faoliyati")),
                ('image', models.ImageField(upload_to='researchers/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': 'Tadqiqotchi (Olim)',
                'verbose_name_plural': 'Tadqiqotchilar (Olimlar)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Yutuq / Ilmiy ish')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Yutuq / Ilmiy ish')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Yutuq / Ilmiy ish')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Yutuq / Ilmiy ish')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='diplomat.researcher')),
            ],
            options={
                'verbose_name': 'Ilmiy yutuq',
                'verbose_name_plural': 'Ilmiy yutuqlar',
                'ordering': ['order'],
            },
        ),
    ]
