# Generated by Django 6.0.3 on 2026-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0013_researcher_researcherachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Ism')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Ism')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Ism')),
                ('surname', models.CharField(max_length=255, verbose_name='Familiya / Otasining ismi')),
                ('surname_uz', models.CharField(max_length=255, null=True, verbose_name='Familiya / Otasining ismi')),
                ('surname_en', models.CharField(max_length=255, null=True, verbose_name='Familiya / Otasining ismi')),
                ('surname_ru', models.CharField(max_length=255, null=True, verbose_name='Familiya / Otasining ismi')),
                ('position', models.CharField(help_text='Masalan: Yoshlar yetakchisi', max_length=255, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(help_text='Masalan: Yoshlar yetakchisi', max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(help_text='Masalan: Yoshlar yetakchisi', max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(help_text='Masalan: Yoshlar yetakchisi', max_length=255, null=True, verbose_name='Lavozimi')),
                ('motto', models.CharField(blank=True, max_length=500, null=True, verbose_name="Bosh g'oya / Shiori")),
                ('motto_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name="Bosh g'oya / Shiori")),
                ('motto_en', models.CharField(blank=True, max_length=500, null=True, verbose_name="Bosh g'oya / Shiori")),
                ('motto_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name="Bosh g'oya / Shiori")),
                ('bio', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('bio_uz', models.TextField(null=True, verbose_name="Qisqacha ma'lumot")),
                ('bio_en', models.TextField(null=True, verbose_name="Qisqacha ma'lumot")),
                ('bio_ru', models.TextField(null=True, verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(upload_to='council/', verbose_name='Rasm')),
                ('badge_icon', models.CharField(blank=True, help_text='Masalan: fas fa-crown', max_length=100, null=True, verbose_name='Badge ikonka')),
                ('bg_icon', models.CharField(blank=True, help_text='Masalan: fas fa-chess-king', max_length=100, null=True, verbose_name='Fon ikonka (katta)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': "Kengash a'zosi",
                'verbose_name_plural': "Kengash a'zolari",
                'ordering': ['order'],
            },
        ),
    ]
