# Generated by Django 6.0.3 on 2026-04-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0014_councilmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH.')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('position', models.CharField(help_text='Masalan: REKTOR, PROREKTOR, BOSH DIREKTOR', max_length=255, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(help_text='Masalan: REKTOR, PROREKTOR, BOSH DIREKTOR', max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(help_text='Masalan: REKTOR, PROREKTOR, BOSH DIREKTOR', max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(help_text='Masalan: REKTOR, PROREKTOR, BOSH DIREKTOR', max_length=255, null=True, verbose_name='Lavozimi')),
                ('degree', models.CharField(blank=True, help_text='Masalan: Siyosiy fanlar doktori, Professor', max_length=255, null=True, verbose_name='Ilmiy daraja')),
                ('degree_uz', models.CharField(blank=True, help_text='Masalan: Siyosiy fanlar doktori, Professor', max_length=255, null=True, verbose_name='Ilmiy daraja')),
                ('degree_en', models.CharField(blank=True, help_text='Masalan: Siyosiy fanlar doktori, Professor', max_length=255, null=True, verbose_name='Ilmiy daraja')),
                ('degree_ru', models.CharField(blank=True, help_text='Masalan: Siyosiy fanlar doktori, Professor', max_length=255, null=True, verbose_name='Ilmiy daraja')),
                ('image', models.ImageField(upload_to='leaders/', verbose_name='Rasm')),
                ('badge_icon', models.CharField(blank=True, default='fas fa-star', help_text='Masalan: fas fa-star', max_length=100, null=True, verbose_name='Badge ikonka')),
                ('reception_time', models.CharField(blank=True, help_text='Masalan: Seshanba - Payshanba (14:00-16:00)', max_length=255, null=True, verbose_name='Qabul vaqti')),
                ('reception_time_uz', models.CharField(blank=True, help_text='Masalan: Seshanba - Payshanba (14:00-16:00)', max_length=255, null=True, verbose_name='Qabul vaqti')),
                ('reception_time_en', models.CharField(blank=True, help_text='Masalan: Seshanba - Payshanba (14:00-16:00)', max_length=255, null=True, verbose_name='Qabul vaqti')),
                ('reception_time_ru', models.CharField(blank=True, help_text='Masalan: Seshanba - Payshanba (14:00-16:00)', max_length=255, null=True, verbose_name='Qabul vaqti')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram havola')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn havola')),
                ('bio_intro', models.TextField(blank=True, help_text="Umumiy ma'lumot — modal ochilib chiqgandagi bosh matn", null=True, verbose_name='Biografiya kirish matni')),
                ('bio_intro_uz', models.TextField(blank=True, help_text="Umumiy ma'lumot — modal ochilib chiqgandagi bosh matn", null=True, verbose_name='Biografiya kirish matni')),
                ('bio_intro_en', models.TextField(blank=True, help_text="Umumiy ma'lumot — modal ochilib chiqgandagi bosh matn", null=True, verbose_name='Biografiya kirish matni')),
                ('bio_intro_ru', models.TextField(blank=True, help_text="Umumiy ma'lumot — modal ochilib chiqgandagi bosh matn", null=True, verbose_name='Biografiya kirish matni')),
                ('bio_degree_text', models.TextField(blank=True, help_text="Ilmiy daraja haqida kengaytirilgan ma'lumot", null=True, verbose_name='Ilmiy daraja (batafsil)')),
                ('bio_degree_text_uz', models.TextField(blank=True, help_text="Ilmiy daraja haqida kengaytirilgan ma'lumot", null=True, verbose_name='Ilmiy daraja (batafsil)')),
                ('bio_degree_text_en', models.TextField(blank=True, help_text="Ilmiy daraja haqida kengaytirilgan ma'lumot", null=True, verbose_name='Ilmiy daraja (batafsil)')),
                ('bio_degree_text_ru', models.TextField(blank=True, help_text="Ilmiy daraja haqida kengaytirilgan ma'lumot", null=True, verbose_name='Ilmiy daraja (batafsil)')),
                ('bio_research_text', models.TextField(blank=True, help_text='Ilmiy ishlari va maqolalari haqida', null=True, verbose_name='Ilmiy faoliyat (batafsil)')),
                ('bio_research_text_uz', models.TextField(blank=True, help_text='Ilmiy ishlari va maqolalari haqida', null=True, verbose_name='Ilmiy faoliyat (batafsil)')),
                ('bio_research_text_en', models.TextField(blank=True, help_text='Ilmiy ishlari va maqolalari haqida', null=True, verbose_name='Ilmiy faoliyat (batafsil)')),
                ('bio_research_text_ru', models.TextField(blank=True, help_text='Ilmiy ishlari va maqolalari haqida', null=True, verbose_name='Ilmiy faoliyat (batafsil)')),
                ('bio_international_text', models.TextField(blank=True, help_text='Xalqaro konferensiyalar va tajriba haqida', null=True, verbose_name='Xalqaro tajriba (batafsil)')),
                ('bio_international_text_uz', models.TextField(blank=True, help_text='Xalqaro konferensiyalar va tajriba haqida', null=True, verbose_name='Xalqaro tajriba (batafsil)')),
                ('bio_international_text_en', models.TextField(blank=True, help_text='Xalqaro konferensiyalar va tajriba haqida', null=True, verbose_name='Xalqaro tajriba (batafsil)')),
                ('bio_international_text_ru', models.TextField(blank=True, help_text='Xalqaro konferensiyalar va tajriba haqida', null=True, verbose_name='Xalqaro tajriba (batafsil)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeaderExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(help_text='Masalan: 2019-2022 yy.', max_length=100, verbose_name="Sana oralig'i")),
                ('date_range_uz', models.CharField(help_text='Masalan: 2019-2022 yy.', max_length=100, null=True, verbose_name="Sana oralig'i")),
                ('date_range_en', models.CharField(help_text='Masalan: 2019-2022 yy.', max_length=100, null=True, verbose_name="Sana oralig'i")),
                ('date_range_ru', models.CharField(help_text='Masalan: 2019-2022 yy.', max_length=100, null=True, verbose_name="Sana oralig'i")),
                ('description', models.TextField(verbose_name='Faoliyat tavsifi')),
                ('description_uz', models.TextField(null=True, verbose_name='Faoliyat tavsifi')),
                ('description_en', models.TextField(null=True, verbose_name='Faoliyat tavsifi')),
                ('description_ru', models.TextField(null=True, verbose_name='Faoliyat tavsifi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='diplomat.leader')),
            ],
            options={
                'verbose_name': 'Mehnat faoliyati',
                'verbose_name_plural': 'Mehnat faoliyati',
                'ordering': ['order'],
            },
        ),
    ]
