# Generated by Django 6.0.3 on 2026-04-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0015_leader_leaderexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('kafedra', 'Kafedra'), ('bolim', "Bo'lim")], max_length=20, verbose_name='Turi')),
                ('head_name', models.CharField(max_length=255, verbose_name='Boshliq F.I.SH.')),
                ('head_name_uz', models.CharField(max_length=255, null=True, verbose_name='Boshliq F.I.SH.')),
                ('head_name_en', models.CharField(max_length=255, null=True, verbose_name='Boshliq F.I.SH.')),
                ('head_name_ru', models.CharField(max_length=255, null=True, verbose_name='Boshliq F.I.SH.')),
                ('head_position', models.CharField(help_text='M-n: Kafedra mudiri', max_length=255, verbose_name='Boshliq lavozimi')),
                ('head_position_uz', models.CharField(help_text='M-n: Kafedra mudiri', max_length=255, null=True, verbose_name='Boshliq lavozimi')),
                ('head_position_en', models.CharField(help_text='M-n: Kafedra mudiri', max_length=255, null=True, verbose_name='Boshliq lavozimi')),
                ('head_position_ru', models.CharField(help_text='M-n: Kafedra mudiri', max_length=255, null=True, verbose_name='Boshliq lavozimi')),
                ('head_image', models.ImageField(upload_to='departments/', verbose_name='Boshliq rasmi')),
                ('description', models.TextField(help_text='Boshliq yoki kafedra haqida batafsil matn', verbose_name='Tavsif (Biografiya / Malumot)')),
                ('description_uz', models.TextField(help_text='Boshliq yoki kafedra haqida batafsil matn', null=True, verbose_name='Tavsif (Biografiya / Malumot)')),
                ('description_en', models.TextField(help_text='Boshliq yoki kafedra haqida batafsil matn', null=True, verbose_name='Tavsif (Biografiya / Malumot)')),
                ('description_ru', models.TextField(help_text='Boshliq yoki kafedra haqida batafsil matn', null=True, verbose_name='Tavsif (Biografiya / Malumot)')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': "Kafedra / Bo'lim",
                'verbose_name_plural': "Kafedralar va Bo'limlar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH.')),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='F.I.SH.')),
                ('position', models.CharField(help_text="M-n: Kafedra o'qituvchisi", max_length=255, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(help_text="M-n: Kafedra o'qituvchisi", max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(help_text="M-n: Kafedra o'qituvchisi", max_length=255, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(help_text="M-n: Kafedra o'qituvchisi", max_length=255, null=True, verbose_name='Lavozimi')),
                ('image', models.ImageField(upload_to='employees/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('bio_uz', models.TextField(null=True, verbose_name='Biografiya')),
                ('bio_en', models.TextField(null=True, verbose_name='Biografiya')),
                ('bio_ru', models.TextField(null=True, verbose_name='Biografiya')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='diplomat.department', verbose_name="Kafedra/Bo'lim")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['order'],
            },
        ),
    ]
