# Generated by Django 6.0.3 on 2026-04-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0016_department_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='M-n: Yangiliklar, Tahliliy materiallar', max_length=255, verbose_name='Turkum nomi')),
                ('title_uz', models.CharField(help_text='M-n: Yangiliklar, Tahliliy materiallar', max_length=255, null=True, verbose_name='Turkum nomi')),
                ('title_en', models.CharField(help_text='M-n: Yangiliklar, Tahliliy materiallar', max_length=255, null=True, verbose_name='Turkum nomi')),
                ('title_ru', models.CharField(help_text='M-n: Yangiliklar, Tahliliy materiallar', max_length=255, null=True, verbose_name='Turkum nomi')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': 'Yangilik turkumi',
                'verbose_name_plural': 'Yangilik turkumlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='URL Slug')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('badge', models.CharField(blank=True, help_text='M-n: Dolzarb, Xalqaro', max_length=100, null=True, verbose_name='Yorliq (Badge)')),
                ('badge_uz', models.CharField(blank=True, help_text='M-n: Dolzarb, Xalqaro', max_length=100, null=True, verbose_name='Yorliq (Badge)')),
                ('badge_en', models.CharField(blank=True, help_text='M-n: Dolzarb, Xalqaro', max_length=100, null=True, verbose_name='Yorliq (Badge)')),
                ('badge_ru', models.CharField(blank=True, help_text='M-n: Dolzarb, Xalqaro', max_length=100, null=True, verbose_name='Yorliq (Badge)')),
                ('badge_color', models.CharField(default='#FFC107', help_text='M-n: #ff6b6b, #0d6efd, #FFC107', max_length=50, verbose_name='Yorliq rangi')),
                ('excerpt', models.TextField(help_text="Sahifada ro'yxatda ko'rinadigan qisqacha mazmun", verbose_name='Qisqacha matn')),
                ('excerpt_uz', models.TextField(help_text="Sahifada ro'yxatda ko'rinadigan qisqacha mazmun", null=True, verbose_name='Qisqacha matn')),
                ('excerpt_en', models.TextField(help_text="Sahifada ro'yxatda ko'rinadigan qisqacha mazmun", null=True, verbose_name='Qisqacha matn')),
                ('excerpt_ru', models.TextField(help_text="Sahifada ro'yxatda ko'rinadigan qisqacha mazmun", null=True, verbose_name='Qisqacha matn')),
                ('content', models.TextField(verbose_name="To'liq matn")),
                ('content_uz', models.TextField(null=True, verbose_name="To'liq matn")),
                ('content_en', models.TextField(null=True, verbose_name="To'liq matn")),
                ('content_ru', models.TextField(null=True, verbose_name="To'liq matn")),
                ('author', models.CharField(default='Matbuot Xizmati', max_length=255, verbose_name="Muallif yoki bo'lim")),
                ('author_uz', models.CharField(default='Matbuot Xizmati', max_length=255, null=True, verbose_name="Muallif yoki bo'lim")),
                ('author_en', models.CharField(default='Matbuot Xizmati', max_length=255, null=True, verbose_name="Muallif yoki bo'lim")),
                ('author_ru', models.CharField(default='Matbuot Xizmati', max_length=255, null=True, verbose_name="Muallif yoki bo'lim")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('published_date', models.DateField(verbose_name='Chop etilgan sana')),
                ('is_published', models.BooleanField(default=True, verbose_name="Saytda ko'rinishi")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_set', to='diplomat.newscategory', verbose_name='Turkum')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_date', '-id'],
            },
        ),
    ]
