# Generated by Django 6.0.3 on 2026-04-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0017_newscategory_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='badge_color',
        ),
    ]
