# Generated by Django 6.0.3 on 2026-04-10 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0018_remove_news_badge_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('style_1', 'Video fon (1-slayd uslubi)'), ('style_2', 'Cyber va Rasm (2-slayd uslubi)'), ('style_3', "Prestige va Qo'shimcha karta (3-slayd uslubi)"), ('style_4', 'Gradient va Uchta blok (4-slayd uslubi)')], default='style_1', max_length=20, verbose_name='Slayd uslubi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('badge_text', models.CharField(blank=True, max_length=150, verbose_name='Nishon matni (Badge)')),
                ('badge_text_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nishon matni (Badge)')),
                ('badge_text_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nishon matni (Badge)')),
                ('badge_text_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nishon matni (Badge)')),
                ('title_part_1', models.CharField(max_length=150, verbose_name='Sarlavha 1-qismi')),
                ('title_part_1_uz', models.CharField(max_length=150, null=True, verbose_name='Sarlavha 1-qismi')),
                ('title_part_1_en', models.CharField(max_length=150, null=True, verbose_name='Sarlavha 1-qismi')),
                ('title_part_1_ru', models.CharField(max_length=150, null=True, verbose_name='Sarlavha 1-qismi')),
                ('title_part_2', models.CharField(blank=True, max_length=150, verbose_name='Sarlavha ajratilgan qismi (Highlight/Glitch)')),
                ('title_part_2_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha ajratilgan qismi (Highlight/Glitch)')),
                ('title_part_2_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha ajratilgan qismi (Highlight/Glitch)')),
                ('title_part_2_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha ajratilgan qismi (Highlight/Glitch)')),
                ('title_part_3', models.CharField(blank=True, max_length=150, verbose_name='Sarlavha 3-qismi')),
                ('title_part_3_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha 3-qismi')),
                ('title_part_3_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha 3-qismi')),
                ('title_part_3_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha 3-qismi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('button_text', models.CharField(blank=True, default='BATAFSIL', max_length=100, verbose_name='Tugma matni')),
                ('button_text_uz', models.CharField(blank=True, default='BATAFSIL', max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_en', models.CharField(blank=True, default='BATAFSIL', max_length=100, null=True, verbose_name='Tugma matni')),
                ('button_text_ru', models.CharField(blank=True, default='BATAFSIL', max_length=100, null=True, verbose_name='Tugma matni')),
                ('modal_target', models.CharField(blank=True, max_length=50, verbose_name='Modal Oyna ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sliders/', verbose_name='Orqa fon rasmi')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='sliders/', verbose_name='Orqa fon videoga (Faqat 1-uslub)')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='sliders/', verbose_name='Video poster (Cover)')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Ikonka klassi (Masalan: fas fa-rocket)')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Sarlavha')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Qisqacha matni')),
                ('description_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha matni')),
                ('description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha matni')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='diplomat.slider')),
            ],
            options={
                'verbose_name': 'Slayder xususiyati',
                'verbose_name_plural': 'Slayder xususiyatlari',
                'ordering': ['order'],
            },
        ),
    ]
