# Generated by Django 6.0.3 on 2026-04-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0019_slider_sliderfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderfeature',
            options={'ordering': ['order'], 'verbose_name': "Qo'shimcha kartochka (3 va 4 uslub uchun)", 'verbose_name_plural': "Qo'shimcha kartochkalar (Faqat 3 va 4 uslublarda ishlaydi)"},
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Modal Quyi Sarlavha'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modal Quyi Sarlavha'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modal Quyi Sarlavha'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_subtitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modal Quyi Sarlavha'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Modal Sarlavha 1'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_1_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Modal Sarlavha 1'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_1_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Modal Sarlavha 1'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_1_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Modal Sarlavha 1'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Modal Sarlavha 2 (Ajratilgan)'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_2_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Modal Sarlavha 2 (Ajratilgan)'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_2_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Modal Sarlavha 2 (Ajratilgan)'),
        ),
        migrations.AddField(
            model_name='slider',
            name='modal_title_part_2_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Modal Sarlavha 2 (Ajratilgan)'),
        ),
        migrations.CreateModel(
            name='SliderModalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Ikonka (Masalan: fas fa-rocket)')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Matni')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modal_items', to='diplomat.slider')),
            ],
            options={
                'verbose_name': 'Modal ichki kartochkasi',
                'verbose_name_plural': 'Modal ichki kartochkalari',
                'ordering': ['order'],
            },
        ),
    ]
