# Generated by Django 6.0.3 on 2026-04-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0020_alter_sliderfeature_options_slider_modal_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='modal_subtitle',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_subtitle_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_subtitle_uz',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_1_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_1_ru',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_1_uz',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_2_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_2_ru',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='modal_title_part_2_uz',
        ),
    ]
