# Generated by Django 6.0.3 on 2026-04-10 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0021_remove_slider_modal_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Sessiya kaliti')),
                ('fullname', models.CharField(max_length=255, verbose_name='Ism va Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Chat suhbat',
                'verbose_name_plural': 'Chat suhbatlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Xabar matni')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='Admin tomonidan')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='diplomat.chatconversation', verbose_name='Suhbat')),
            ],
            options={
                'verbose_name': 'Chat xabar',
                'verbose_name_plural': 'Chat xabarlar',
                'ordering': ['created_at'],
            },
        ),
    ]
