# Generated by Django 6.0.3 on 2026-04-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0022_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Qabul, Moliya', max_length=255, verbose_name='Turkum nomi')),
                ('title_uz', models.CharField(help_text='Masalan: Qabul, Moliya', max_length=255, null=True, verbose_name='Turkum nomi')),
                ('title_en', models.CharField(help_text='Masalan: Qabul, Moliya', max_length=255, null=True, verbose_name='Turkum nomi')),
                ('title_ru', models.CharField(help_text='Masalan: Qabul, Moliya', max_length=255, null=True, verbose_name='Turkum nomi')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Tab Slug (Inglizcha, kichik harfda)')),
                ('icon', models.CharField(help_text='Masalan: fas fa-file-alt', max_length=100, verbose_name='Turkum Ikonkasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': 'FAQ Turkumi',
                'verbose_name_plural': 'FAQ Turkumlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('question_uz', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('question_en', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('question_ru', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('answer', models.TextField(help_text='HTML teglar (masalan: <strong>, <a>) ishlatish mumkin', verbose_name='Javob')),
                ('answer_uz', models.TextField(help_text='HTML teglar (masalan: <strong>, <a>) ishlatish mumkin', null=True, verbose_name='Javob')),
                ('answer_en', models.TextField(help_text='HTML teglar (masalan: <strong>, <a>) ishlatish mumkin', null=True, verbose_name='Javob')),
                ('answer_ru', models.TextField(help_text='HTML teglar (masalan: <strong>, <a>) ishlatish mumkin', null=True, verbose_name='Javob')),
                ('icon', models.CharField(blank=True, help_text='Masalan: fas fa-calendar-check', max_length=100, null=True, verbose_name='Savol Ikonkasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faolmi (Saytda ko'rinadimi)?")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='diplomat.faqcategory', verbose_name='Turkum')),
            ],
            options={
                'verbose_name': 'FAQ Savol',
                'verbose_name_plural': 'FAQ Savollar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
