# Generated by Django 6.0.3 on 2026-04-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0023_faqcategory_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hamkor nomi')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Hamkor raqsi (Logosi)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', '-id'],
            },
        ),
    ]
