# Generated by Django 6.0.3 on 2026-04-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0024_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programapproach',
            name='program',
        ),
    ]
