# Generated by Django 6.0.3 on 2026-04-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0025_remove_programapproach_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharif')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('completed', 'Yakunlandi')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ariza vaqti')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='diplomat.program', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "Yo'nalish arizasi",
                'verbose_name_plural': "Yo'nalish arizalari",
                'ordering': ['-created_at'],
            },
        ),
    ]
