# Generated by Django 6.0.3 on 2026-04-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0026_programapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL uchun)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
            ],
            options={
                'verbose_name': "Do'kon kategoriyasi",
                'verbose_name_plural': "Do'kon kategoriyalari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('image', models.ImageField(upload_to='shop/', verbose_name='Rasm')),
                ('price', models.PositiveIntegerField(verbose_name="Narxi (so'm)")),
                ('old_price', models.PositiveIntegerField(blank=True, help_text="Chegirma bo'lsa eski narxni kiriting", null=True, verbose_name="Eski narxi (so'm)")),
                ('badge', models.CharField(blank=True, choices=[('', "Yo'q"), ('YANGI', 'YANGI'), ('HOT', 'HOT'), ('-10%', '-10%'), ('-15%', '-15%'), ('-20%', '-20%'), ('-25%', '-25%'), ('-30%', '-30%'), ('-50%', '-50%')], default='', help_text='Masalan: YANGI, -15%', max_length=50, verbose_name='Yorliq (Badge)')),
                ('rating', models.PositiveIntegerField(default=5, help_text='1 dan 5 gacha yulduz', verbose_name='Reyting (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faolmi (saytda ko'rinadimi)?")),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqam')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='diplomat.shopcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': "Do'kon mahsuloti",
                'verbose_name_plural': "Do'kon mahsulotlari",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
