# Generated by Django 6.0.3 on 2026-04-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0027_shopcategory_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('address', models.TextField(blank=True, verbose_name='Manzili (Yetkazib berish uchun)')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name="Jami summa (so'm)")),
                ('status', models.CharField(choices=[('new', 'Yangi (Kutilmoqda)'), ('processing', 'Jarayonda'), ('shipped', 'Yetkazilmoqda'), ('completed', 'Tugallangan/Yetkazib berilgan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
            ],
            options={
                'verbose_name': "Do'kon buyurtmasi",
                'verbose_name_plural': "Do'kon buyurtmalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi (Saqlangan)')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tanlangan rang')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name="Tanlangan o'lcham")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('price', models.PositiveIntegerField(verbose_name="Donasining narxi (so'm)")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diplomat.shoporder', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diplomat.shopproduct', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma qilingan mahsulot',
                'verbose_name_plural': 'Buyurtma qilingan mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ShopProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Oq, Qora, Qizil', max_length=100, verbose_name='Rang nomi')),
                ('name_uz', models.CharField(help_text='Masalan: Oq, Qora, Qizil', max_length=100, null=True, verbose_name='Rang nomi')),
                ('name_en', models.CharField(help_text='Masalan: Oq, Qora, Qizil', max_length=100, null=True, verbose_name='Rang nomi')),
                ('name_ru', models.CharField(help_text='Masalan: Oq, Qora, Qizil', max_length=100, null=True, verbose_name='Rang nomi')),
                ('color_code', models.CharField(default='#FFFFFF', help_text='Masalan: #FFFFFF, #000000', max_length=50, verbose_name='Rang kodi (HEX)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='diplomat.shopproduct', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rangi',
                'verbose_name_plural': 'Mahsulot ranglari',
            },
        ),
        migrations.CreateModel(
            name='ShopProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: S, M, L, XL, XXL, 42, 44', max_length=50, verbose_name="O'lcham")),
                ('name_uz', models.CharField(help_text='Masalan: S, M, L, XL, XXL, 42, 44', max_length=50, null=True, verbose_name="O'lcham")),
                ('name_en', models.CharField(help_text='Masalan: S, M, L, XL, XXL, 42, 44', max_length=50, null=True, verbose_name="O'lcham")),
                ('name_ru', models.CharField(help_text='Masalan: S, M, L, XL, XXL, 42, 44', max_length=50, null=True, verbose_name="O'lcham")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='diplomat.shopproduct', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "Mahsulot o'lchami",
                'verbose_name_plural': "Mahsulot o'lchamlari",
            },
        ),
    ]
