# Generated by Django 6.0.3 on 2026-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0028_shoporder_shoporderitem_shopproductcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproductcolor',
            name='color_code',
        ),
        migrations.AddField(
            model_name='shopproductcolor',
            name='image',
            field=models.ImageField(default='', help_text='Ushbu rang uchun mahsulot rasmi', upload_to='shop/colors/', verbose_name='Rang rasmi'),
            preserve_default=False,
        ),
    ]
