# Generated by Django 6.0.3 on 2026-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0029_remove_shopproductcolor_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh (Admin uchun)'),
        ),
    ]
