# Generated by Django 6.0.3 on 2026-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0030_shoporder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/details/', verbose_name='Batafsil sahifa rasmi (Ichkari)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name="Ro'yxat sahifasi rasmi (Asosiy)"),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
    ]
