# Generated by Django 6.0.3 on 2026-04-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0031_news_detail_image_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail_image_position_y',
            field=models.IntegerField(default=50, help_text="0 (tepa), 50 (o'rta), 100 (past). Masalan teparoqni ko'rsatish uchun 20-30 qiling.", verbose_name='Ichki rasm joylashuvi Y (%)'),
        ),
    ]
