# Generated by Django 6.0.3 on 2026-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0032_news_detail_image_position_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail_image_position_y',
            field=models.IntegerField(default=50, help_text='0 (tepa), 50 (o\'rta), 100 (past). Masalan teparoqni ko\'rsatish uchun 20-30 qiling. <br><b>Joriy qiymat:</b> <span id="pos_val" style="color:#007bff; font-weight:bold; font-size:16px;">50%</span>', verbose_name='Ichki rasm joylashuvi Y (%)'),
        ),
    ]
