# Generated by Django 6.0.3 on 2026-04-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0033_alter_news_detail_image_position_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_position_y',
            field=models.IntegerField(default=50, help_text='0 (tepa), 50 (o\'rta), 100 (past). Masalan teparoqni ko\'rsatish uchun 20-30 qiling. <br><b>Joriy qiymat:</b> <span id="main_pos_val" style="color:#007bff; font-weight:bold; font-size:16px;"></span><script>document.addEventListener("DOMContentLoaded", function(){ var inp = document.getElementById("id_image_position_y"); if(inp){ document.getElementById("main_pos_val").innerText = inp.value + "%"; } });</script>', verbose_name='Asosiy rasm joylashuvi Y (%)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='detail_image_position_y',
            field=models.IntegerField(default=50, help_text='0 (tepa), 50 (o\'rta), 100 (past). Masalan teparoqni ko\'rsatish uchun 20-30 qiling. <br><b>Joriy qiymat:</b> <span id="pos_val" style="color:#007bff; font-weight:bold; font-size:16px;"></span><script>document.addEventListener("DOMContentLoaded", function(){ var inp = document.getElementById("id_detail_image_position_y"); if(inp){ document.getElementById("pos_val").innerText = inp.value + "%"; } });</script>', verbose_name='Ichki rasm joylashuvi Y (%)'),
        ),
    ]
