# Generated by Django 6.0.3 on 2026-04-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomat', '0034_news_image_position_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail_image_position_y',
            field=models.IntegerField(default=50, help_text='0 (tepa), 50 (o\'rta), 100 (past). Masalan teparoqni ko\'rsatish uchun 20-30 qiling. <br><b>Joriy qiymat:</b> <span id="pos_val" style="color:#007bff; font-weight:bold; font-size:16px;"></span><div id="detail_img_preview" style="width:100%; max-width:400px; height:250px; background-size:cover; background-position:center 50%; border-radius:8px; margin-top:10px; border:2px solid #ddd; display:none; box-shadow:0 4px 10px rgba(0,0,0,0.1);"></div><script>document.addEventListener("DOMContentLoaded", function(){ var inp = document.getElementById("id_detail_image_position_y"); var preview = document.getElementById("detail_img_preview"); var valSpan = document.getElementById("pos_val"); if(inp){ valSpan.innerText = inp.value + "%"; var imgField = document.querySelector(".field-detail_image .file-upload a"); if(imgField){ preview.style.backgroundImage = "url(\'" + imgField.href + "\')"; preview.style.backgroundPosition = "center " + inp.value + "%"; preview.style.display = "block"; } inp.addEventListener("input", function(){ valSpan.innerText = this.value + "%"; preview.style.backgroundPosition = "center " + this.value + "%"; }); var fileInp = document.getElementById("id_detail_image"); if(fileInp){ fileInp.addEventListener("change", function(){ if(this.files && this.files[0]){ var reader = new FileReader(); reader.onload = function(e){ preview.style.backgroundImage = "url(\'" + e.target.result + "\')"; preview.style.display = "block"; }; reader.readAsDataURL(this.files[0]); } }); } } });</script>', verbose_name='Ichki rasm joylashuvi Y (%)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_position_y',
            field=models.IntegerField(default=50, help_text='0 (tepa), 50 (o\'rta), 100 (past). Masalan teparoqni ko\'rsatish uchun 20-30 qiling. <br><b>Joriy qiymat:</b> <span id="main_pos_val" style="color:#007bff; font-weight:bold; font-size:16px;"></span><div id="main_img_preview" style="width:100%; max-width:400px; height:200px; background-size:cover; background-position:center 50%; border-radius:8px; margin-top:10px; border:2px solid #ddd; display:none; box-shadow:0 4px 10px rgba(0,0,0,0.1);"></div><script>document.addEventListener("DOMContentLoaded", function(){ var inp = document.getElementById("id_image_position_y"); var preview = document.getElementById("main_img_preview"); var valSpan = document.getElementById("main_pos_val"); if(inp){ valSpan.innerText = inp.value + "%"; var imgField = document.querySelector(".field-image .file-upload a"); if(imgField){ preview.style.backgroundImage = "url(\'" + imgField.href + "\')"; preview.style.backgroundPosition = "center " + inp.value + "%"; preview.style.display = "block"; } inp.addEventListener("input", function(){ valSpan.innerText = this.value + "%"; preview.style.backgroundPosition = "center " + this.value + "%"; }); var fileInp = document.getElementById("id_image"); if(fileInp){ fileInp.addEventListener("change", function(){ if(this.files && this.files[0]){ var reader = new FileReader(); reader.onload = function(e){ preview.style.backgroundImage = "url(\'" + e.target.result + "\')"; preview.style.display = "block"; }; reader.readAsDataURL(this.files[0]); } }); } } });</script>', verbose_name='Asosiy rasm joylashuvi Y (%)'),
        ),
    ]
